//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdherenceProtocol
    {
        public int smaID { get; set; }
        public int PhaseID { get; set; }
        public Nullable<int> PhaseNext { get; set; }
        public decimal AdhScoreLL { get; set; }
        public Nullable<int> DaysBtMsgs { get; set; }
        public Nullable<int> ReqDaysAdh { get; set; }
        public bool active { get; set; }
        public Nullable<int> PhaseRelapse { get; set; }
        public Nullable<int> DaysToAvg { get; set; }
        public bool Relapse { get; set; }
    }
}
