//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int AdmissionId { get; set; }
        public string UserId { get; set; }
        public int AdmissionTypeId { get; set; }
        public System.DateTime AdmissionDate { get; set; }
    }
}
