//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationSetting
    {
        public int Id { get; set; }
        public string ApplicationName { get; set; }
        public int RootItemId { get; set; }
        public Nullable<int> ThemeId { get; set; }
        public string HeaderTitle { get; set; }
        public string HeaderImage { get; set; }
        public Nullable<int> HeaderFontId { get; set; }
        public Nullable<int> HeaderFontSize { get; set; }
        public string HeaderColor { get; set; }
        public string HeaderBackgroundColor { get; set; }
        public string HeaderBackgroundImage { get; set; }
        public Nullable<decimal> HeaderBackgroundAlpha { get; set; }
        public Nullable<decimal> HeaderBackgroundImageAlpha { get; set; }
        public Nullable<int> HeaderEffect { get; set; }
        public Nullable<int> BackButtonType { get; set; }
        public string BackButtonColor { get; set; }
        public string BackButtonBackgroundColor { get; set; }
        public Nullable<decimal> BackButtonBackgroundAlpha { get; set; }
        public Nullable<int> MenuButtonType { get; set; }
        public string MenuButtonColor { get; set; }
        public string MenuButtonBackgroundColor { get; set; }
        public Nullable<decimal> MenuButtonBackgroundAlpha { get; set; }
        public string SelectedMenuButtonColor { get; set; }
        public string SelectedMenuButtonBackgroundColor { get; set; }
        public Nullable<decimal> SelectedMenuButtonBackgroundAlpha { get; set; }
        public Nullable<int> BodyFontId { get; set; }
        public Nullable<int> BodyFontSize { get; set; }
        public Nullable<int> BodyFontSizeLg { get; set; }
        public Nullable<int> BodyFontSizeSm { get; set; }
        public string BodyColor { get; set; }
        public string SelectedBodyColor { get; set; }
        public string BodyBackgroundColor { get; set; }
        public string BodyBackgroundPortraitImage { get; set; }
        public string BodyBackgroundLandscapeImage { get; set; }
        public Nullable<decimal> BodyBackgroundAlpha { get; set; }
        public Nullable<decimal> BodyBackgroundImageAlpha { get; set; }
        public string SelectedBodyBackgroundColor { get; set; }
        public Nullable<decimal> SelectedBodyBackgroundAlpha { get; set; }
        public Nullable<int> BodySeparatorType { get; set; }
        public string BodySeparatorColor { get; set; }
        public string ButtonColor { get; set; }
        public string ButtonBackgroundColor { get; set; }
        public Nullable<decimal> ButtonBackgroundAlpha { get; set; }
        public string LabelColor { get; set; }
        public string ValidationColor { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
