//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interval
    {
        public int Id { get; set; }
        public int ZoneId { get; set; }
        public System.DateTime UtcStart { get; set; }
        public System.DateTime UtcEnd { get; set; }
        public System.DateTime LocalStart { get; set; }
        public System.DateTime LocalEnd { get; set; }
        public short OffsetMinutes { get; set; }
        public string Abbreviation { get; set; }
    
        public virtual Zone Zone { get; set; }
    }
}
