//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLogic
    {
        public int LogicId { get; set; }
        public int ItemId { get; set; }
        public int EventId { get; set; }
        public int ActionId { get; set; }
        public string Expression { get; set; }
        public string Components { get; set; }
        public Nullable<int> TargetItemId { get; set; }
        public Nullable<int> SelectedMenuItemId { get; set; }
    
        public virtual ItemLogicAction ItemLogicAction { get; set; }
        public virtual ItemLogicEvent ItemLogicEvent { get; set; }
        public virtual Item Item { get; set; }
        public virtual Item Item1 { get; set; }
    }
}
