//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.ApplicationSettings = new HashSet<ApplicationSetting>();
            this.ItemLogics = new HashSet<ItemLogic>();
            this.ItemLogics1 = new HashSet<ItemLogic>();
            this.ItemNavigations = new HashSet<ItemNavigation>();
            this.ItemNavigations1 = new HashSet<ItemNavigation>();
            this.ItemToolbarItems = new HashSet<ItemToolbarItem>();
            this.ToolbarItemNavigations = new HashSet<ToolbarItemNavigation>();
            this.ToolbarItems = new HashSet<ToolbarItem>();
        }
    
        public int ItemId { get; set; }
        public int ItemTypeId { get; set; }
        public string Name { get; set; }
        public int TemplateId { get; set; }
        public string HeaderTitle { get; set; }
        public string HeaderImage { get; set; }
        public Nullable<int> HeaderFontId { get; set; }
        public Nullable<int> HeaderFontSize { get; set; }
        public string HeaderColor { get; set; }
        public string HeaderBackgroundColor { get; set; }
        public string HeaderBackgroundImage { get; set; }
        public Nullable<decimal> HeaderBackgroundAlpha { get; set; }
        public Nullable<decimal> HeaderBackgroundImageAlpha { get; set; }
        public Nullable<int> HeaderEffect { get; set; }
        public Nullable<int> BackButtonType { get; set; }
        public string BackButtonColor { get; set; }
        public string BackButtonBackgroundColor { get; set; }
        public Nullable<decimal> BackButtonBackgroundAlpha { get; set; }
        public Nullable<int> BodyFontId { get; set; }
        public Nullable<int> BodyFontSize { get; set; }
        public string BodyColor { get; set; }
        public string BodyBackgroundColor { get; set; }
        public string BodyBackgroundPortraitImage { get; set; }
        public string BodyBackgroundLandscapeImage { get; set; }
        public Nullable<decimal> BodyBackgroundAlpha { get; set; }
        public Nullable<decimal> BodyBackgroundImageAlpha { get; set; }
        public Nullable<System.DateTime> CreatedDateUTC { get; set; }
        public string CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateUTC { get; set; }
        public string LastUpdatedById { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationSetting> ApplicationSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLogic> ItemLogics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLogic> ItemLogics1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemNavigation> ItemNavigations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemNavigation> ItemNavigations1 { get; set; }
        public virtual ItemTemplate ItemTemplate { get; set; }
        public virtual ItemType ItemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemToolbarItem> ItemToolbarItems { get; set; }
        public virtual Survey Survey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolbarItemNavigation> ToolbarItemNavigations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolbarItem> ToolbarItems { get; set; }
    }
}
