//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginInformation
    {
        public int LoginInformationId { get; set; }
        public string UserId { get; set; }
        public System.DateTimeOffset DateDTO { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Model { get; set; }
        public string OS { get; set; }
        public string Network { get; set; }
        public string PhoneType { get; set; }
        public string AppVersion { get; set; }
        public string DateCTZ { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
