//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicationActivity
    {
        public int ActivityId { get; set; }
        public int ActivityTypeId { get; set; }
        public System.DateTime ActivityUTC { get; set; }
        public System.DateTimeOffset ActivityDTO { get; set; }
        public string ActivityCTZ { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<int> UserMedicationId { get; set; }
        public string UserId { get; set; }
    
        public virtual LU_MedicationActivityTypes LU_MedicationActivityTypes { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual UserMedication UserMedication { get; set; }
        public virtual User User { get; set; }
    }
}
