//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message1
    {
        public int MessageId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public string Error { get; set; }
        public System.DateTime DateSentUTC { get; set; }
        public Nullable<int> TokenId { get; set; }
    
        public virtual DeviceToken DeviceToken { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
