//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationPreference
    {
        public string UserId { get; set; }
        public Nullable<int> NotificationTypeId { get; set; }
        public Nullable<int> NotificationDays { get; set; }
        public int NotificationPreferencesId { get; set; }
    
        public virtual LU_NotificationType LU_NotificationType { get; set; }
        public virtual User User { get; set; }
    }
}
