//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationMessage
    {
        public int NotificationMessageId { get; set; }
        public string UserId { get; set; }
        public int NotificationTypeId { get; set; }
        public System.DateTime NotificationDateUTC { get; set; }
        public Nullable<int> TokenId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DeviceToken DeviceToken { get; set; }
        public virtual LU_NotificationType LU_NotificationType { get; set; }
    }
}
