//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedPhase
    {
        public int sphID { get; set; }
        public string userID { get; set; }
        public int phaseID { get; set; }
        public Nullable<System.DateTime> adhDate { get; set; }
        public bool adherence { get; set; }
        public Nullable<int> phaseDayCount { get; set; }
        public System.DateTime dateEntered { get; set; }
    }
}
