//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public int PhoneNumberId { get; set; }
        public string UserId { get; set; }
        public string Transplant { get; set; }
        public string Study { get; set; }
        public string Pharmacy { get; set; }
        public string Refill { get; set; }
    }
}
