//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Survey()
        {
            this.SurveyAnswers = new HashSet<SurveyAnswer>();
            this.SurveyQuestions = new HashSet<SurveyQuestion>();
            this.SurveySessions = new HashSet<SurveySession>();
        }
    
        public int SurveyId { get; set; }
        public bool AllowRestart { get; set; }
        public bool AutoSubmit { get; set; }
        public string ListColor { get; set; }
        public string ListBackgroundColor { get; set; }
        public Nullable<decimal> ListBackgroundAlpha { get; set; }
        public Nullable<int> ListFontId { get; set; }
        public Nullable<int> ListFontSize { get; set; }
        public string SelectedColor { get; set; }
        public string SelectedBackgroundColor { get; set; }
        public Nullable<decimal> SelectedBackgroundAlpha { get; set; }
        public Nullable<int> SelectedFontId { get; set; }
        public Nullable<int> SelectedFontSize { get; set; }
        public Nullable<int> SelectedIconType { get; set; }
        public string SelectedIconColor { get; set; }
        public string ButtonColor { get; set; }
        public string ButtonBackgroundColor { get; set; }
        public Nullable<decimal> ButtonBackgroundAlpha { get; set; }
        public Nullable<int> ButtonFontId { get; set; }
        public Nullable<int> ButtonFontSize { get; set; }
        public string ProgressBarColor { get; set; }
        public string ProgressBarBackgroundColor { get; set; }
        public Nullable<decimal> ProgressBarBackgroundAlpha { get; set; }
        public string TooltipColor { get; set; }
        public string TooltipBackgroundColor { get; set; }
        public Nullable<decimal> TooltipBackgroundAlpha { get; set; }
        public Nullable<int> TooltipFontId { get; set; }
        public Nullable<int> TooltipFontSize { get; set; }
        public string FeedbackColor { get; set; }
        public string FeedbackBackgroundColor { get; set; }
        public Nullable<decimal> FeedbackBackgroundAlpha { get; set; }
        public Nullable<int> FeedbackFontId { get; set; }
        public Nullable<int> FeedbackFontSize { get; set; }
        public string SeparatorColor { get; set; }
    
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyAnswer> SurveyAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyQuestion> SurveyQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveySession> SurveySessions { get; set; }
    }
}
