//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveySession()
        {
            this.SurveyAnswers = new HashSet<SurveyAnswer>();
        }
    
        public int SessionId { get; set; }
        public int SurveyId { get; set; }
        public string UserId { get; set; }
        public System.DateTime StartDateUTC { get; set; }
        public Nullable<System.DateTimeOffset> StartDateDTO { get; set; }
        public string StartDateCTZ { get; set; }
        public Nullable<System.DateTime> EndDateUTC { get; set; }
        public Nullable<System.DateTimeOffset> EndDateDTO { get; set; }
        public string EndDateCTZ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyAnswer> SurveyAnswers { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual User User { get; set; }
    }
}
