//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyQuestionLogic
    {
        public int LogicId { get; set; }
        public int QuestionId { get; set; }
        public int ActionId { get; set; }
        public Nullable<int> ActionQuestionId { get; set; }
        public string Expression { get; set; }
        public string Components { get; set; }
    
        public virtual SurveyQuestionLogicAction SurveyQuestionLogicAction { get; set; }
    }
}
