//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyAnswer
    {
        public int AnswerId { get; set; }
        public int SurveyId { get; set; }
        public string UserId { get; set; }
        public int SessionId { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> OptionId { get; set; }
        public Nullable<int> OptionValue { get; set; }
        public string AnswerText { get; set; }
        public Nullable<System.DateTimeOffset> AnswerDateDTO { get; set; }
        public System.DateTime AnswerDateUTC { get; set; }
        public string AnswerDateCTZ { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual SurveyQuestionCategory SurveyQuestionCategory { get; set; }
        public virtual SurveyQuestionOption SurveyQuestionOption { get; set; }
        public virtual SurveyQuestion SurveyQuestion { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual SurveySession SurveySession { get; set; }
        public virtual User User { get; set; }
    }
}
