//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyOption
    {
        public int OptionId { get; set; }
        public int GroupId { get; set; }
        public string OptionText { get; set; }
        public Nullable<int> OptionValue { get; set; }
        public int OptionOrder { get; set; }
    
        public virtual SurveyOptionGroup SurveyOptionGroup { get; set; }
    }
}
