//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyQuestionOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyQuestionOption()
        {
            this.SurveyAnswers = new HashSet<SurveyAnswer>();
        }
    
        public int OptionId { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string OptionText { get; set; }
        public string OptionImage { get; set; }
        public int OptionValue { get; set; }
        public int OptionOrder { get; set; }
        public Nullable<int> ShapeType { get; set; }
        public string Coordinates { get; set; }
        public string Feedback { get; set; }
        public string FeedbackColor { get; set; }
        public string FeedbackBackgroundColor { get; set; }
        public Nullable<decimal> FeedbackBackgroundAlpha { get; set; }
        public Nullable<int> FeedbackFontId { get; set; }
        public Nullable<int> FeedbackFontSize { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Font Font { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyAnswer> SurveyAnswers { get; set; }
        public virtual SurveyQuestionCategory SurveyQuestionCategory { get; set; }
        public virtual SurveyQuestion SurveyQuestion { get; set; }
    }
}
