//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolbarItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolbarItem()
        {
            this.ItemToolbarItems = new HashSet<ItemToolbarItem>();
            this.ToolbarItemNavigations = new HashSet<ToolbarItemNavigation>();
        }
    
        public int ToolbarItemId { get; set; }
        public string Name { get; set; }
        public int ActionId { get; set; }
        public string ItemText { get; set; }
        public string Icon { get; set; }
        public Nullable<int> TargetItemId { get; set; }
        public Nullable<int> SelectedMenuItemId { get; set; }
        public Nullable<int> NavigationTypeId { get; set; }
        public Nullable<int> TransitionTypeId { get; set; }
    
        public virtual ItemNavigationType ItemNavigationType { get; set; }
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemToolbarItem> ItemToolbarItems { get; set; }
        public virtual ItemTransitionType ItemTransitionType { get; set; }
        public virtual ToolbarItemAction ToolbarItemAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolbarItemNavigation> ToolbarItemNavigations { get; set; }
    }
}
