//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolbarItemNavigation
    {
        public int NavigationId { get; set; }
        public int ToolbarItemId { get; set; }
        public int TargetItemId { get; set; }
        public Nullable<int> SelectedMenuItemId { get; set; }
        public int Priority { get; set; }
        public int NavigationTypeId { get; set; }
        public int TransitionTypeId { get; set; }
        public string LogicExpression { get; set; }
        public string LogicComponents { get; set; }
    
        public virtual ItemNavigationType ItemNavigationType { get; set; }
        public virtual Item Item { get; set; }
        public virtual ItemTransitionType ItemTransitionType { get; set; }
        public virtual ToolbarItem ToolbarItem { get; set; }
    }
}
