//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransafeRx.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMedication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMedication()
        {
            this.MedicationActivities = new HashSet<MedicationActivity>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int UserMedicationId { get; set; }
        public string UserId { get; set; }
        public string DrugName { get; set; }
        public string Instructions { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Route { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> CreatedDateUTC { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDateDTO { get; set; }
        public string CreatedDateCTZ { get; set; }
        public Nullable<System.DateTime> UpdatedDateUTC { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedDateDTO { get; set; }
        public string UpdatedDateCTZ { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string GPI { get; set; }
        public string Frequency { get; set; }
        public string dosage { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicationActivity> MedicationActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
